config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'product', to: 'pages#product'

  get 'submission', to: 'pages#submission'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end

  def product
  end

  def submission
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta property="og:image" content="TODO">
    <meta property="og:description" content="Hadley Innovation is a scientific research company specialized in weather index insurance design">
    <meta property="og:title" content="Hadley Innovation">
    <title>Hadley Innovation</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700">
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
  <!-- Navigation -->
    <div class="filter">
      <nav class="navbar navbar-fixed-top" role="navigation">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <%= link_to(image_tag("logo.png", :alt => "Home", class: "logo"), '/')%>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to "Description", product_path %>
                    </li>
                    <li>
                      <%= link_to "Team", about_path %>
                    </li>
                    <li>
                      <%= link_to "Contact", contact_path %>
                    </li>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>
    </div>
      <!-- Footer -->
      <div class="footer">
        <div class="footer-content">
          <div class="tag">
            <p><em>Hadley Innovation is a research company specialized in weather index insurance design.</em></p>
          </div>
          <div class="footer-icons">
            <div class="footer-icon-logo-first">
              <%= link_to(image_tag("facebook_F.svg", :alt => "facebook"), 'https://www.facebook.com/hadleyinnovation', target: '_blank')%>
            </div>
            <div class="footer-icon-logo">
              <%= link_to(image_tag("twitter_F.svg", :alt => "twitter"), 'https://twitter.com/hadleyinno', target: '_blank')%>
            </div>
            <div class="footer-icon-logo">
              <%= link_to(image_tag("email_F.svg", :alt => "email"), 'contact')%>
            </div>
            <div class="footer-icon-logo-last">
              <%= link_to(image_tag("LinkedIn.svg", :alt => "LinkedIn"), 'https://www.linkedin.com/company/hadley-innovation', target: '_blank')%>
            </div>
          </div>
          <div class="copyright">
            <p>Copyright &copy; 2016 Hadley Innovation</p>
          </div>
        </div>
      </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <!-- Team Members -->
  <div class="row">
      <div class="col-lg-12">
          <h2 class="page-header">Who are we</h2>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
            <%= image_tag "profil_pic_Flo", id: "logo", class: "florian" %>
              <div class="caption florian">
                  <h3>Florian Cochard<br>
                      <small>CEO</small>
                  </h3>
                  <p>Florian Cochard is a graduate in meteorology and post-graduate in entrepreneurship. His expertise allows to cross the gap between scientific research and market challenges.</p>
                  <ul class="list-inline media-icons">
                      <li><a href="https://www.linkedin.com/in/floriancochard"><i class="fa fa-2x fa-linkedin-square"></i></a>
                      </li>
                      <li><a href="https://twitter.com/florian_cochard"><i class="fa fa-2x fa-twitter-square"></i></a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
            <%= image_tag "profil_pic_Jm", id: "logo", class: "jean-marie" %>
              <div class="caption jean-marie">
                  <h3>Jean-Marie Lepioufle<br>
                      <small>CTO</small>
                  </h3>
                  <p>Jean Marie Lepioufle holds a PhD in stochastic meteorology. His expertise in geostatistics allows to address specific market expectations.</p>
                  <ul class="list-inline media-icons">
                      <li><a href="https://no.linkedin.com/in/jeanmarielepioufle"><i class="fa fa-2x fa-linkedin-square"></i></a>
                      </li>
                      <li><a href="https://twitter.com/jmlepioufle"><i class="fa fa-2x fa-twitter-square"></i></a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
              <%= image_tag "profil_pic_Lau", id: "logo", class: "laurianne" %>
              <div class="caption laurianne">
                  <h3>Laurianne Gerin<br>
                      <small>Junior Developer</small>
                  </h3>
                  <p>Laurianne Gerin is a graduate in Oceanography and in web development. Her expertise in science and design allows to be more transparent and understandable.</p>
                  <ul class="list-inline media-icons">
                      <li><a href="https://fr.linkedin.com/in/laurianne-gerin-5a86b093/en"><i class="fa fa-2x fa-linkedin-square"></i></a>
                      </li>
                      <li><a href="https://twitter.com/lauceanbrille"><i class="fa fa-2x fa-twitter-square"></i></a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
            <%= image_tag "empty_avatar", id: "logo", class: "empty-avatar" %>
              <div class="caption">
                  <h3>This could be you<br>
                      <small>Rainfall Modeler</small>
                  </h3>
                  <a href="contact" class="btn btn-default submit-btn">Ask us</a>
              </div>
          </div>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
            <%= image_tag "empty_avatar", id: "logo", class: "empty-avatar" %>
              <div class="caption">
                  <h3>This could be you<br>
                      <small>Crop Modeler</small>
                  </h3>
                  <a href="contact" class="btn btn-default submit-btn">Ask us</a>
              </div>
          </div>
      </div>
      <div class="col-md-4 text-center">
          <div class="thumbnail">
            <%= image_tag "empty_avatar", id: "logo", class: "empty-avatar" %>
              <div class="caption">
                  <h3>This could be you<br>
                      <small>Insurance Expert</small>
                  </h3>
                  <a href="contact" class="btn btn-default submit-btn">Ask us</a>
              </div>
          </div>
      </div>
  </div>
  <!-- /.row -->

  <!-- Our Sponsors -->
  <!-- <div class="row">
      <div class="col-lg-12">
          <h2 class="page-header">Our Sponsors</h2>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
          <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
      </div>
  </div> -->
  <!-- /.row -->
</div>

app/views/pages/contact.html.erb
<div class="contact-form">
  <div class="container">
    <div class"contact-intro">
      <h2>Contact us</h2>
      <p> Hadley Innovation is constantly seeking for new addition to the team. If you wish to contact us, don't hesitate to send a message through the contact form below, we will answer you in less than a day.
      </p>
    </div>
    <form action="https://formform.herokuapp.com/f/nosatave" method="POST">
      <div class="form-group">
        <label for="name">Name</label>
        <input type="name" class="form-control" id="name" placeholder="Name" name="name">
      </div>
      <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
      </div>
      <div class="form-group">
        <label for="subject">Subject</label>
        <input type="subject" class="form-control" id="subject" placeholder="Subject" name="subject">
      </div>
      <div class="form-group">
        <label for="subject">Message</label>
        <textarea class="form-control" rows="10" placeholder="Your message" name="message"></textarea>
      </div>
      <button type="submit" class="btn btn-default pull-right submit-btn">Submit</button>
        </form>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Landing Image Section -->
<div class='welcome-banner text-center'>
  <h1>HADLEY</h1>
  <h3>innovation</h3>
</div>


<!-- Page Content -->
<div class="container">
  <div>
    <div class="punchline">
      <p class="introduction-phrase">
        Hadley Innovation is a research company specialized in weather insurance design.
      </p>
      <hr class="line">
      <p>
        Our vision is to leverage the index insurance market and to allow the 50 million smallholders farmers across sub-Saharan Africa to benefit from a cheap, transparent and tailor-made insurance product.
      </p>
    </div>
  </div>
  <!-- Features Section -->
  <section class="home--section">
      <div>
          <h2 class="page-header">Context</h2>
      </div>
      <div class="home--description">
        <div class="home--content">
          <p>Most farmers in developing countries practice rain-fed agriculture. Not enough rain means plants don’t produce a harvest while too much rain can kill
            growing crops. To protect against natural hazards and climate risk, farmers can insure themselves.
          </p>
          <p>Yet the existing network of low rain density gauges and the short historical time periods prevent a suitable risk coverage.
          </p>
        </div>
        <div class="home--picture">
            <%= image_tag "context-hadley.jpg", alt: "Problem of Hadley Innovation" %>
        </div>
      </div>
  </section>

  <section class="home--section">
      <div>
          <h2 class="page-header">Solution</h2>
      </div>
      <div class="home--description">
        <div class="home--picture">
          <%= image_tag "solution-hadley.png", alt: "Solution of Hadley Innovation" %>
        </div>
        <div class="home--content">
          <p>Hadley Innovation overcomes the challenge of missing information, by simulating realistic rainfall data. Known as <em>stochastic modeling of space-time rainfall field, </em>
            our simulator accounts for the spatial and temporal dependence of rainfall patterns.
          </p>
          <p>From ground observations measurements, statistical analysis of rainfall distribution is first achieved to infer input parameters in the rainfall simulator.
            In output, relevant information are generated at locations with no previous measurements, or where only short data series are available. Synthetic rainfall
            data improve weather index design while lowering premiums' costs, making insurance more affordable.
          </p>
        </div>
      </div>
  </section>

  <section class="home--section">
      <div>
          <h2 class="page-header">Vision</h2>
      </div>
      <div class="home--description">
        <div class="home--content">
          <p>Allowing the 50 million smallholders farmers across sub-Saharan Africa to benefit from cheap, transparent and tailor-made
            insurance coverage against climate risk. The model Hadley Innovation is developing represents a small part of what needs to be achieved to
            properly design and price a weather index. Cross disciplinary collaborations from different disciplines - geostatistics, climatology, agronomy and finance
            - are thus required to end-up with a whole product with strong value for smallholders’ farmers.
          </p>
          <div class="text-center read-more">
            <a href="product" class="btn btn-default btn-submit">Read More</a>
          </div>
        </div>
        <div class="home--picture">
            <%= image_tag "vision-hadley.jpg", alt: "Vision of Hadley Innovation" %>
        </div>
      </div>
  </section>
  <!-- /.row -->
  <div class="row">
  </div>
</div>

app/views/pages/submission.html.erb
<div class="contact-form">
  <div class="container">
    <div class="message-panel text-center">
      <div class"message">
        <h3>
          Message sent :)
        </h3>
        <p>We will take the time to read and answer your message as soon as possible !</p>
        <p>Kind regards,</p>
        <p>Hadley Innovation Team</p>
        </p>
    </div>
    </div>
  </div>
</div>